# Generated by Django 4.2.30 on 2026-07-11 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('author', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('recipe_yield', models.CharField(blank=True, max_length=50)),
                ('prep_time', models.CharField(blank=True, max_length=20)),
                ('cook_time', models.CharField(blank=True, max_length=20)),
                ('total_time', models.CharField(blank=True, max_length=20)),
                ('recipe_category', models.CharField(blank=True, max_length=100)),
                ('ingredients', models.TextField(blank=True)),
                ('instructions', models.TextField(blank=True)),
            ],
        ),
    ]
