# Generated by Django 4.2.30 on 2026-07-12 11:42

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_is_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='CookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cooked_on', models.DateField(default=datetime.date.today)),
                ('rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, '★'), (2, '★★'), (3, '★★★'), (4, '★★★★'), (5, '★★★★★')], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cook_logs', to='recipes.recipe')),
            ],
            options={
                'ordering': ['-cooked_on', '-created_at'],
            },
        ),
    ]
