# Generated by Django 4.2.30 on 2026-08-15 14:14

from django.db import migrations, models
import recipes.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_cooklog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, upload_to=recipes.models.recipe_image_upload_path),
        ),
    ]
